CREATE TABLE Uploads (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Email NVARCHAR(255) NOT NULL,
  Nickname NVARCHAR(50) NOT NULL,
  Photo VARBINARY(MAX) NOT NULL,
  CreatedAt DATETIME DEFAULT GETDATE()
);
